---

- hosts: all
  become: true
  tasks: 

  - name: install apache,php,nfs,update package
    yum:
      name:
        - httpd
        - php
        - bind-utils
      update_cache: yes
      state: latest

  - name: install updates
    yum:
      update_only: yes
      update_cache: yes
 
- hosts: web_server
  become: true
  tasks:

  - name: install mariadb package 
    yum:
      name: mariadb
      state: latest

  - name: copy html file for site
    tags: apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
