---

- hosts: all
  become: true
  tasks: 

  - name: update repo
    yum:
      update_cache: yes

  - name: install apache package
    yum:
      name: httpd
      state: latest
  - name: install php support for httpd
    yum:
      name: mod_php
      state: latest
