---

- hosts: all
  become: true
  tasks: 

  - name: install apache,php,nfs,update package
    yum:
      name:
        - httpd
        - php
        - bind-utils
      update_cache: yes
      state: latest

  - name: install updates
    yum:
      update_only: yes
      update_cache: yes
 
- hosts: file_server
  become: true
  tasks:

  - name: install mariadb package 
    yum:
      name: mariadb
      state: latest
